version: '2'
services:
  api:
    image: "agapeteo/visualtext"
    ports:
     - "8080:8080"
    links:
    - hazelcast
    environment:
    - HAZELCAST_SERVER=hazelcast
    depends_on:
    - hazelcast
  hazelcast:
      image: "agapeteo/hazelcast-zookeeper-member"
      ports:
       - "5701"
      links:
      - zookeeper
      environment:
      - ZOOKEEPER_URL=zookeeper:2181
      depends_on:
      - zookeeper
  zookeeper:
      image: "zookeeper"
      ports:
      - "2181:2181"
