replicaCount: 3
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate
image:
  repository: agapeteo/visualtext
  tag: 1.0.4
  pullPolicy: IfNotPresent
  livenessProbe:
    path: /health
    port: 8080
    initialDelaySeconds: 50
    timeoutSeconds: 15
    periodSeconds: 30
  readinessProbe:
    path: /health
    port: 8080
    initialDelaySeconds: 50
    timeoutSeconds: 15
service:
  name: web-port
  type: NodePort
  externalPort: 8080
  internalPort: 8080
java:
  xmx: -Xmx512m
resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi
restartPolicy: Always
hpa:
  maxReplicas: 7
  minReplicas: 2
  targetCPUUtilizationPercentage: 60