replicaCount: 3
strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
  type: RollingUpdate
image:
  repository: agapeteo/visualtext
  tag: 1.0.2
  env:
    name: HAZELCAST_SERVER
    value: hazelcast
  pullPolicy: IfNotPresent
  livenessProbe:
    path: /health
    port: 8080
    initialDelaySeconds: 50
    timeoutSeconds: 15
    periodSeconds: 30
  readinessProbe:
    path: /health
    port: 8080
    initialDelaySeconds: 50
    timeoutSeconds: 15
service:
  name: web-port
  type: NodePort
  externalPort: 8080
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 250m
    memory: 250Mi
restartPolicy: Always
hpa:
  maxReplicas: 7
  minReplicas: 2
  targetCPUUtilizationPercentage: 60