apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ template "fullname" . }}
              servicePort: 80
            path: /