apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hazelcast
  name: hazelcast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hazelcast
      name: hazelcast
    spec:
      containers:
      - name: hazelcast
        image: agapeteo/hazelcast-zookeeper-member:1.0.0
        env:
        - name: ZOOKEEPER_URL
          value: zookeeper:2181
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

