apiVersion: v1
kind: Service
metadata:
  labels:
    app: hazelcast
  name: hazelcast
spec:
  ports:
  - name: hazelcast-port
    port: 5701
    protocol: TCP
    targetPort: 5701
  selector:
    app: hazelcast
  type: ClusterIP

