apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-nginx
  name: test-nginx
spec:
  ports:
  - name: webui-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-nginx
  type: LoadBalancer
