apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-nginx
  name: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-nginx
      name: test-nginx
    spec:
      containers:
      - name: test-nginx
        image: kupolua/webui:0.1
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf/conf.d
        env:
        - name: GIT_REPO_URL
          value: "https://github.com/kupolua/visualtext.git"
        - name: GIT_BRANCH
          value: "master"
        - name: GIT_REPO_SYNC_TIME
          value: "10"
        - name: WEBUI_PATH
          value: "webui/html"
        - name: API_HOST
          value: "visualtext-api.default.svc.cluster.local"
        - name: API_PORT
          value: "8080"
      volumes:
        - name: config
          configMap:
            name: test-nginx-config
      restartPolicy: Always