apiVersion: v1
kind: Service
metadata:
  labels:
    app: visualtext-api
  name: visualtext-api
spec:
  ports:
  - name: web-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: visualtext-api
  type: NodePort