apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: visualtext-api
  name: visualtext-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualtext-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: visualtext-api
      name: visualtext-api
    spec:
      containers:
      - name: visualtext-api
        image: agapeteo/visualtext:1.0.2
        env:
        - name: HAZELCAST_SERVER
          value: hazelcast
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 50
          timeoutSeconds: 15
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 50
          timeoutSeconds: 15
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 250Mi
            cpu: 250m
      restartPolicy: Always

