apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name "config" | trunc 63 }}
data:
  application.properties: |
      giphy.url=http://api.giphy.com/v1/gifs/search
      giphy.key=dc6zaTOxFJmzC&limit=1
      giphy.imageType=fixed_width

