apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: {{ .Values.image.env.host.name }}
          value: "{{ .Values.image.env.host.deployment }}-{{ .Values.image.env.host.apiservice }}"
        - name: {{ .Values.image.env.portname }}
          value: "{{ .Values.image.env.portvalue }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      restartPolicy: {{ .Values.restartPolicy }}