apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "zk" | trunc 63 }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}"
spec:
  ports:
  - port: {{.Values.ServerPort}}
    name: server
  - port: {{.Values.LeaderElectionPort}}
    name: leader-election
  clusterIP: None
  type: NodePort
  selector:
    component: "{{.Release.Name}}"

